---
- name: Get Ceph FSID
  command:
    cmd: "cephadm shell -- ceph fsid"
  become: true
  register: cephadm_destroy_fsid
  changed_when: false
  failed_when: false
  when: inventory_hostname == cephadm_bootstrap_host

- name: Destroy cluster
  vars:
    fsid_result: "{{ hostvars[cephadm_bootstrap_host].cephadm_destroy_fsid }}"
  command:
    cmd: "cephadm rm-cluster --fsid {{ fsid_result.stdout }} --force"
  become: true
  changed_when: true
  when: fsid_result.rc != 1

- name: Remove ssh keys
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cephadm_ssh_private_key }}"
    - "{{ cephadm_ssh_public_key }}"
  become: true
