---
- name: "Destroy cephadm deployment"
  include_tasks: "destroy.yml"
  when:
    - cephadm_recreate | bool

- name: "Run prechecks"
  include_tasks: "prechecks.yml"
  when: not cephadm_skip_prechecks | bool

- name: "Install packages"
  include_tasks: "pkg_{{ ansible_facts.os_family | lower }}.yml"

- name: "Bootstrap prereqs"
  include_tasks: "prereqs_bootstrap.yml"
  when:
    - inventory_hostname == cephadm_bootstrap_host

- name: "Prereq tasks"
  import_tasks: "prereqs.yml"

- name: "Bootstrap"
  include_tasks: "bootstrap.yml"
  when:
    - cephadm_bootstrap | bool
    - inventory_hostname == cephadm_bootstrap_host

- name: "Add osds individually"
  import_tasks: "osds.yml"

- name: "Ensure osd spec is defined"
  include_tasks: "osds_spec.yml"
  when:
    - cephadm_osd_spec | length > 0
    - inventory_hostname == cephadm_bootstrap_host
