---
- name: Get cluster fsid
  command:
    cmd: "cephadm shell -- ceph fsid"
  when: cephadm_fsid | length == 0
  become: true
  register: cephadm_fsid_current
  changed_when: false

- name: Template out osd_spec.yml
  vars:
    fsid: "{{ cephadm_fsid if cephadm_fsid | length > 0 else cephadm_fsid_current.stdout }}"
  copy:
    content: "{{ cephadm_osd_spec | to_nice_yaml if cephadm_osd_spec is mapping else cephadm_osd_spec }}"
    dest: "/var/run/ceph/{{ fsid }}/osd_spec.yml"
    owner: root
    group: root
    mode: "0o644"
  become: true

- name: Apply OSDs spec
  command:
    cmd: >
         cephadm shell --
         ceph orch apply -i /var/run/ceph/osd_spec.yml
  become: true
  changed_when: true
